language: rust

matrix:
  include:
    - rust: stable
      env: CHECK_FMT=y
    - rust: beta
    - rust: nightly
    - rust: nightly
      env: CHECK_CLIPPY=y
  allow_failures:
    - rust: nightly
      env: CHECK_CLIPPY=y
  fast_finish: true

cache:
  cargo: true

install:
  - if [ ! -z "$CHECK_FMT" ]; then (cargo install rustfmt | true); fi
  - if [ ! -z "$CHECK_CLIPPY" ]; then (cargo install --force clippy | true); fi

before_script:
  - if [ ! -z "$CHECK_FMT" ]; then PATH=$PATH:~/.cargo/bin cargo fmt -- --write-mode=diff; fi
  - if [ ! -z "$CHECK_CLIPPY" ]; then PATH=$PATH:~/.cargo/bin cargo clippy -- -D clippy; fi
