[package]
name = "french-numbers"
description = "Represent numbers in French language"
keywords = ["text", "french", "numbers"]
license = "Apache-2.0/MIT"
homepage = "https://rfc1149.net/devel/french-numbers.html"
documentation = "https://docs.rs/french-numbers/"
version = "1.1.5-pre"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
categories = ["value-formatting"]
readme = "README.md"
edition = "2021"

[dependencies]
num-integer = "0.1.45"
num-traits = "0.2.16"

[dev-dependencies]
clap = { version = "4.4.6", features = ["derive"] }
num-bigint = "0.4.4"
proptest = "1.3.1"

# Fake dependency to avoid depending on a non-compiling older version
proc-macro2 = "1.0.68"
