[package]
name = "french-numbers"
description = "Represent numbers in French language"
keywords = ["text", "french", "numbers"]
license = "Apache-2.0/MIT"
homepage = "https://rfc1149.net/devel/french-numbers.html"
documentation = "https://docs.rs/french-numbers/"
version = "1.1.5-pre"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
categories = ["value-formatting"]
readme = "README.md"
edition = "2021"

[dependencies]
num-integer = "0.1.41"
num-traits = "0.2.8"

[dev-dependencies]
clap = { version = "4.0.8", features = ["derive"] }
num-bigint = "0.4.0"
proptest = "1.0.0"
