sign-commit = true
sign-tag = true
pre-release-replacements = [{file = "README.md", search="french-numbers = \".*\"", replace="french-numbers = \"{{version}}\""}]
dev-version = true
dev-version-ext = "pre"
